Repository Apollonyan/CS193p-Developing-Apps-for-iOS-Spring-2020, pull requests merged in 2020-06, with the labels that each got.

#43 翻译第一集 1334 - 1384 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成

#29 翻译第 1 集 850 - 901 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 待修改

#42 翻译第 1 集 1105 - 1154 条字幕
  subtitles/en/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#24 翻译第 1 集 646 - 796 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 翻译完成

#44 翻译第 1 集 1385 - 1422 条字幕
  subtitles/en/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#45 翻译第 2 集 201 - 250 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 初校完成

#41 翻译第 1 集 1285 - 1333 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成

#32 翻译第 1 集 555 - 605 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#48 翻译第 2 集 5 - 150 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 初校中

#51 翻译第 2 集 151 - 200 条字幕
  subtitles/en/Lecture 2. MVVM and the Swift Type System.srt
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 翻译完成

#50 第一集定稿
  subtitles/en/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 精校中

#55 翻译第 2 集 351 - 500 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#56 翻译第 2 集 501 - 600 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#58 翻译第 2 集 251 - 350 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#60 翻译第 2 集 816 - 866 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#57 翻译第 2 集 701 - 815 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改
