Repository Apollonyan/CS193p-Developing-Apps-for-iOS-Spring-2020, pull requests merged in 2020-05, with the labels that each got.

#6 翻译第 1 集 94 - 140 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 待解决

#10 第一课 192~202翻译
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 翻译完成

#8 翻译第 1 集 141 - 191 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 待修改, 翻译完成

#3 翻译第 1 集 5 - 52 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校中

#13 翻译第 1 集 203 - 253 条字幕
  subtitles/en/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改, 翻译完成

#15 翻译第 1 集 254 - 302 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 翻译完成

#21 Fix Episode 1 line 284, 286, 287, 289, 292
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
  translation-style-guide.md
Labels: 待修改

#17 翻译第 1 集 53 - 93 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 待修改, 翻译完成

#22 翻译第 1 集 606 - 625 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#19 翻译第 1 集 303 - 453 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 翻译完成

#25 翻译第 1 集 797 - 816 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#27 翻译第 1 集 902 - 931 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 待修改

#34 翻译第一集 1074 - 1104 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改, 翻译完成

#31 翻译第 1 集 1023 - 1073 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改, 翻译完成

#37 翻译第一集 1203 - 1243 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 翻译完成

#39 纠正文件编码 + 移除空格
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 工具链

#35 翻译第 1 集 454 - 554 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 翻译完成

#38 翻译第1集 1155 - 1202 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改

#36 翻译第1集 626 - 645 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改, 翻译完成

#28 翻译第 1 集 932 - 1022 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 初校完成, 翻译完成

#40 翻译第一集 1244 - 1284 条字幕
  subtitles/zh-Hans/Lecture 1. Course Logistics and Introduction to SwiftUI.srt
Labels: 待修改
