Repository Apollonyan/CS193p-Developing-Apps-for-iOS-Spring-2020, pull requests merged in 2020-07, with the labels that each got.

#70 翻译第 2 集 1240 - 1285 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 完成：初校, 完成：翻译

#67 翻译第 2 集 967 - 1007 条字幕
  subtitles/en/Lecture 2. MVVM and the Swift Type System.srt
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 完成：翻译, 待修改

#66 翻译第 2 集 1008 - 1088 条字幕
  subtitles/en/Lecture 2. MVVM and the Swift Type System.srt
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 完成：翻译, 待修改

#69 翻译第 2 集 1286 - 1386 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 完成：翻译, 待修改

#54 翻译第 2 集 601 - 650 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#62 翻译第 2 集 867 - 899 条字幕
  subtitles/en/Lecture 2. MVVM and the Swift Type System.srt
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 完成：翻译

#71 翻译第 2 集 1387 - 1485 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改

#61 翻译第 2 集 651 - 700 条字幕
  subtitles/zh-Hans/Lecture 2. MVVM and the Swift Type System.srt
Labels: 待修改
